Enable history in Allure

diff --git a/.github/workflows/playwright.yaml b/.github/workflows/playwright.yaml
--- a/.github/workflows/playwright.yaml
+++ b/.github/workflows/playwright.yaml
@@ -19,18 +19,35 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Check Current Branch
+      - name: Debug Git Branches
         run: |
-          echo "Full ref: $GITHUB_REF"
-          echo "Branch name: ${GITHUB_REF##*/}"
+          echo "Before fetching:"
+          git branch -a
+          git fetch origin
+          echo "After fetching:"
+          git branch -a
 
       - name: Retrieve Allure History
         run: |
+          # Fetch and check out allure-history
           git fetch origin allure-history
           git checkout allure-history
           mkdir -p allure-results
-          cp -r ./reports/allure/history allure-results/history
-          git checkout merge
+          cp -r ./reports/allure/history allure-results/history || echo "No history to copy"
+
+          # Return to the original branch
+          ORIGINAL_BRANCH="${GITHUB_REF##*/}"
+          echo "Original branch: $ORIGINAL_BRANCH"
+          git fetch origin $ORIGINAL_BRANCH:$ORIGINAL_BRANCH || echo "Branch '$ORIGINAL_BRANCH' not found"
+          git checkout $ORIGINAL_BRANCH || echo "Failed to switch back to branch '$ORIGINAL_BRANCH'"
+
+      - name: Debug Git Branches
+        run: |
+          echo "Before fetching:"
+          git branch -a
+          git fetch origin
+          echo "After fetching:"
+          git branch -a
 
       - name: Run Playwright tests
         run: npm run test --ignore-scripts
